name: MuZero Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous que votre fichier requirements.txt est mis à jour pour inclure toutes les dépendances

    - name: Deploy controllers
      run: |
        python deploy.py  # Ce script déploie les contrôleurs sur la base des emplacements optimisés
